### ISSUE TITLE
expand one item by default

### ISSUE THREAD

**Issue by mays123** [Armani2015/expandable-recyclerview-with-gridlayout#1]
first of all thank you for implementing this nice expandable recyclerview
i want to know how to make the first item expanded by default when i first open the activity??

**Comment by fabricethilaw** [comment]
Hi
To  expand first item, you just add the line below in onCreate(Bundle savedInstanceState) method.
 `mRecyclerViewExpandableItemManager.expandGroup(0);`

You can see an implementation of this with my  new commit. Let me know if that works for you.

**Comment by mays123** [comment]
thank you very much, you made my day
